//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsDSQ
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mauricioreyna.com.ar/", ConfigurationName="wsDSQ.wsDataServiceQuerySoap")]
    public interface wsDataServiceQuerySoap
    {
        
        // CODEGEN: Generating message contract since element name sXmlMessage from namespace http://www.mauricioreyna.com.ar/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mauricioreyna.com.ar/getDataMessage", ReplyAction="*")]
        wsDSQ.getDataMessageResponse getDataMessage(wsDSQ.getDataMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mauricioreyna.com.ar/getDataMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<wsDSQ.getDataMessageResponse> getDataMessageAsync(wsDSQ.getDataMessageRequest request);
        
        // CODEGEN: Generating message contract since element name getParametersResult from namespace http://www.mauricioreyna.com.ar/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mauricioreyna.com.ar/getParameters", ReplyAction="*")]
        wsDSQ.getParametersResponse getParameters(wsDSQ.getParametersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mauricioreyna.com.ar/getParameters", ReplyAction="*")]
        System.Threading.Tasks.Task<wsDSQ.getParametersResponse> getParametersAsync(wsDSQ.getParametersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataMessage", Namespace="http://www.mauricioreyna.com.ar/", Order=0)]
        public wsDSQ.getDataMessageRequestBody Body;
        
        public getDataMessageRequest()
        {
        }
        
        public getDataMessageRequest(wsDSQ.getDataMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mauricioreyna.com.ar/")]
    public partial class getDataMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sXmlMessage;
        
        public getDataMessageRequestBody()
        {
        }
        
        public getDataMessageRequestBody(string sXmlMessage)
        {
            this.sXmlMessage = sXmlMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDataMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDataMessageResponse", Namespace="http://www.mauricioreyna.com.ar/", Order=0)]
        public wsDSQ.getDataMessageResponseBody Body;
        
        public getDataMessageResponse()
        {
        }
        
        public getDataMessageResponse(wsDSQ.getDataMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mauricioreyna.com.ar/")]
    public partial class getDataMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDataMessageResult;
        
        public getDataMessageResponseBody()
        {
        }
        
        public getDataMessageResponseBody(string getDataMessageResult)
        {
            this.getDataMessageResult = getDataMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getParametersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getParameters", Namespace="http://www.mauricioreyna.com.ar/", Order=0)]
        public wsDSQ.getParametersRequestBody Body;
        
        public getParametersRequest()
        {
        }
        
        public getParametersRequest(wsDSQ.getParametersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getParametersRequestBody
    {
        
        public getParametersRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getParametersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getParametersResponse", Namespace="http://www.mauricioreyna.com.ar/", Order=0)]
        public wsDSQ.getParametersResponseBody Body;
        
        public getParametersResponse()
        {
        }
        
        public getParametersResponse(wsDSQ.getParametersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.mauricioreyna.com.ar/")]
    public partial class getParametersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getParametersResult;
        
        public getParametersResponseBody()
        {
        }
        
        public getParametersResponseBody(string getParametersResult)
        {
            this.getParametersResult = getParametersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface wsDataServiceQuerySoapChannel : wsDSQ.wsDataServiceQuerySoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class wsDataServiceQuerySoapClient : System.ServiceModel.ClientBase<wsDSQ.wsDataServiceQuerySoap>, wsDSQ.wsDataServiceQuerySoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsDataServiceQuerySoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsDataServiceQuerySoapClient.GetBindingForEndpoint(endpointConfiguration), wsDataServiceQuerySoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsDataServiceQuerySoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsDataServiceQuerySoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsDataServiceQuerySoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsDataServiceQuerySoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsDataServiceQuerySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsDSQ.getDataMessageResponse wsDSQ.wsDataServiceQuerySoap.getDataMessage(wsDSQ.getDataMessageRequest request)
        {
            return base.Channel.getDataMessage(request);
        }
        
        public string getDataMessage(string sXmlMessage)
        {
            wsDSQ.getDataMessageRequest inValue = new wsDSQ.getDataMessageRequest();
            inValue.Body = new wsDSQ.getDataMessageRequestBody();
            inValue.Body.sXmlMessage = sXmlMessage;
            wsDSQ.getDataMessageResponse retVal = ((wsDSQ.wsDataServiceQuerySoap)(this)).getDataMessage(inValue);
            return retVal.Body.getDataMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsDSQ.getDataMessageResponse> wsDSQ.wsDataServiceQuerySoap.getDataMessageAsync(wsDSQ.getDataMessageRequest request)
        {
            return base.Channel.getDataMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsDSQ.getDataMessageResponse> getDataMessageAsync(string sXmlMessage)
        {
            wsDSQ.getDataMessageRequest inValue = new wsDSQ.getDataMessageRequest();
            inValue.Body = new wsDSQ.getDataMessageRequestBody();
            inValue.Body.sXmlMessage = sXmlMessage;
            return ((wsDSQ.wsDataServiceQuerySoap)(this)).getDataMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsDSQ.getParametersResponse wsDSQ.wsDataServiceQuerySoap.getParameters(wsDSQ.getParametersRequest request)
        {
            return base.Channel.getParameters(request);
        }
        
        public string getParameters()
        {
            wsDSQ.getParametersRequest inValue = new wsDSQ.getParametersRequest();
            inValue.Body = new wsDSQ.getParametersRequestBody();
            wsDSQ.getParametersResponse retVal = ((wsDSQ.wsDataServiceQuerySoap)(this)).getParameters(inValue);
            return retVal.Body.getParametersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsDSQ.getParametersResponse> wsDSQ.wsDataServiceQuerySoap.getParametersAsync(wsDSQ.getParametersRequest request)
        {
            return base.Channel.getParametersAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsDSQ.getParametersResponse> getParametersAsync()
        {
            wsDSQ.getParametersRequest inValue = new wsDSQ.getParametersRequest();
            inValue.Body = new wsDSQ.getParametersRequestBody();
            return ((wsDSQ.wsDataServiceQuerySoap)(this)).getParametersAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsDataServiceQuerySoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsDataServiceQuerySoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsDataServiceQuerySoap))
            {
                return new System.ServiceModel.EndpointAddress("http://wsdataservicequery.mauricioreyna.com.ar/wsDataServiceQuery.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsDataServiceQuerySoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://wsdataservicequery.mauricioreyna.com.ar/wsDataServiceQuery.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsDataServiceQuerySoap,
            
            wsDataServiceQuerySoap12,
        }
    }
}
